language: scala
scala:
  - 2.12.12
jdk: openjdk11

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - echo $TRAVIS_SCALA_VERSION
  - sbt clean coverage test
  - sbt scalafmtCheck

after_success:
  - sbt coverageReport coveralls
  - echo $TRAVIS_TAG
  - sbt set version := $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: $ENCRYPTED_API_KEY
  skip_cleanup: true
  on:
    tags: true
