language: scala
scala:
  - 2.12.12
jdk:
  - openjdk8
  - openjdk11

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt clean coverage test
  - sbt scalafmtCheck

after_success:
  - sbt coverageReport coveralls
  - |
    if [ ! -z $TRAVIS_TAG ]; then
      sbt "set version := \"$TRAVIS_TAG\"" packArchive
    fi

deploy:
  provider: releases
  api_key:
    secure: "CK5L8+M9mE+V083UU+GZ8fcieG7Cwq/ksk+P99V1MLJRiJcm+jFPJMx5TVBuhCW2jFIf4XlnLzpmpJtERIOPEo+oi7RprAzz8kbAKFc/MNfrVrAXolpY29jx8O7kW76BigiVQ7VtpXC37Thqg4TAcZ6dh9ltg33iUX3CHHu2sFq79wiNmFQ5Yj19kqoCnMX+FB7aOtpgYz6FuKCASXIXM4K/O621Qtofll/qJyls0vqK/83Fm8g4OFt8CaW8Ky7HLgorMnTZe6sqhPTTETAhYkUJVZ+R27CpsqIfzEle3+mV5zibjOdqFrn3OYLMRoyX2HBAXPDdT87kDw/K0x6t7EdMd4nJXwA2okZP+aN5RfuXBuN/raGJMpP9D1EhcmK9G7a1aS806Fk19qx058R5ug1BDOHoVR1LqCHeWIDrHDNrwB1Vv22RzYbMp3JlqJy3Ep3fxZ1qZlXMwOW8yG5tL/oZMxkoWIAWz2+IblGtazgec48/Mdm9qndN3Hv1FXWMkoCFTZWYzFqLBAHXUqgzx0KIsK8Kwn8tFhmwuIyBbk9sAt5+mi9tH4dZPLUC3dwdT/36sLimFhmfNHnidNaBr4UsInqk+/QHNkYK+cWNdW2as6VTLHImK91pTo8+xH1371N2FuHb9OLLI3xJWV0ONcuQ/CaY7rmKknFWdevfYjM="
  file:
    - "$TRAVIS_BUILD_DIR/target/kafkaquery-$TRAVIS_TAG.tar.gz"
    - "$TRAVIS_BUILD_DIR/target/kafkaquery-$TRAVIS_TAG.zip"
  skip_cleanup: true
  on:
    tags: true
